
name: Ultra Fast PixelOS Build for denniz

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧼 [5%] Clean runner (Free up to 35GB space)
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/lib/jvm
          sudo apt purge -y dotnet* aspnetcore* || true
          df -h

      - name: ⛰️ [10%] Use /mnt for build (faster + more space)
        run: |
          sudo mkdir -p /mnt/workspace
          sudo chown -R $USER:$USER /mnt/workspace
          echo "WORKDIR=/mnt/workspace" >> $GITHUB_ENV

      - name: ⚡ [15%] Install build essentials (lean & fast)
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk git curl python3 bc bison flex build-essential \
            g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev \
            liblz4-tool libncurses5-dev libssl-dev libxml2-utils lzop pngcrush rsync schedtool \
            squashfs-tools xsltproc zip zlib1g-dev libtinfo5 ccache
          sudo curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
          sudo chmod +x /usr/local/bin/repo
          echo "✅ [20%] Dependencies done"

      - name: 📥 [30%] Init + shallow sync source (fastest)
        run: |
          mkdir -p $WORKDIR/pixelos && cd $WORKDIR/pixelos
          repo init -u https://github.com/PixelOS-AOSP/manifest -b fourteen --depth=1
          echo "🔁 Syncing sources with 8 threads..."
          repo sync -j8 --force-sync --no-tags --no-clone-bundle
          echo "✅ [55%] PixelOS source ready"

      - name: 📁 [60%] Clone device/vendor/kernel trees
        run: |
          cd $WORKDIR/pixelos
          git clone --depth=1 https://github.com/CHIRU195/device_oneplus_denniz.git -b fourteen device/oneplus/denniz
          git clone --depth=1 https://github.com/CHIRU195/vendor_oneplus_denniz.git -b fourteen vendor/oneplus/denniz
          git clone --depth=1 https://github.com/CHIRU195/kernel_oneplus_mt6877.git -b fourteen kernel/oneplus/mt6877
          echo "✅ [65%] Trees cloned"

      - name: ⚙️ [70%] Setup env + lunch
        run: |
          cd $WORKDIR/pixelos
          source build/envsetup.sh
          lunch aosp_denniz-userdebug
          echo "✅ [75%] Lunch ready"

      - name: 🚀 [80%] Build with 16 threads + cache
        run: |
          cd $WORKDIR/pixelos
          export TZ=Asia/Kolkata
          export KBUILD_BUILD_USER=chiru
          export KBUILD_BUILD_HOST=github-ci
          export USE_CCACHE=1
          export CCACHE_EXEC=$(which ccache)
          ccache -M 20G
          echo "💥 Building with max threads..."
          mka bacon -j16
          echo "✅ [95%] Build complete"

      - name: 📦 [100%] Upload ROM output
        uses: actions/upload-artifact@v4
        with:
          name: PixelOS-Denniz-Output
          path: ${{ env.WORKDIR }}/pixelos/out/target/product/denniz/*.zip
