name: PixelOS Sync Sources

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-22.04

    steps:
      - name: Clean system space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/lib/jvm || true
          sudo apt clean && sudo apt autoremove -y || true

      - name: Install repo + essentials
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk git curl python3 build-essential bc bison flex \
            g++-multilib gcc-multilib libncurses5-dev libtinfo5 libssl-dev \
            rsync zip unzip zlib1g-dev ccache lz4
          curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/local/bin/repo
          sudo chmod +x /usr/local/bin/repo

      - name: Repo init and sync
        run: |
          mkdir -p ~/pixelos && cd ~/pixelos
          repo init -u https://github.com/PixelOS-AOSP/manifest -b fourteen --depth=1
          repo sync -c --no-tags --no-clone-bundle -j8

      - name: Upload synced sources
        uses: actions/upload-artifact@v4
        with:
          name: synced-source
          path: ~/pixelos
