name: Build PixelOS for denniz

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git wget curl python3 gcc clang lz4 zstd bc bison flex zip unzip repo ccache openjdk-17-jdk

    - name: Setup Git
      run: |
        git config --global user.email "CHIRUDOC2001@GMAIL.com"
        git config --global user.name "CHIRU195"

    - name: Init and sync source
      run: |
        mkdir -p ~/pixelos
        cd ~/pixelos
        repo init -u https://github.com/PixelOS-AOSP/manifest -b fourteen
        repo sync -j8 --force-sync

    - name: Clone device trees
      run: |
        cd ~/pixelos
        git clone https://github.com/CHIRU195/device_oneplus_denniz.git device/oneplus/denniz
        git clone https://github.com/CHIRU195/vendor_oneplus_denniz.git vendor/oneplus/denniz
        git clone https://github.com/CHIRU195/kernel_oneplus_mt6877.git kernel/oneplus/mt6877

    - name: Lunch config
      run: |
        source build/envsetup.sh
        lunch aosp_denniz-userdebug

    - name: Build ROM
      run: |
        mka bacon

    - name: Upload ROM output
      uses: actions/upload-artifact@v3

      with:
        name: PixelOS-denniz-ROM
        path: out/target/product/denniz/*.zip
